version: '3.7'

services:
  identifier:
    image: mu-identifier:mac
  dispatcher:
    platform: linux/amd64
  database:
    image: mu-authorization:mac
  virtuoso:
    platform: linux/amd64
  resource:
    platform: linux/amd64
  migrations:
    platform: linux/amd64
  deltanotifier:
    platform: linux/amd64
  mocklogin:
    platform: linux/amd64
  file:
    platform: linux/amd64
  person-uri-for-social-security-number:
    platform: linux/amd64
  login:
    platform: linux/amd64
  form-content:
    platform: linux/amd64
  mandataris-archive:
    platform: linux/amd64
  frontend:
    platform: linux/amd64
  cache:
    platform: linux/amd64
